ARG BASE_IMAGE="ghcr.io/gbraad-devenv/ubuntu/dotfiles"
ARG BASE_VERSION="noble"

FROM ${BASE_IMAGE}:${BASE_VERSION}

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/ubuntu-golang"

USER root

RUN apt-get update \
    && apt-get install -y \
        golang \
        delve \
    && rm -rf /var/lib/apt/lists/*
