ARG BASE_IMAGE="ghcr.io/gbraad-devenv/ubuntu-golang/dotfiles"
ARG BASE_VERSION="noble"

FROM ${BASE_IMAGE}:${BASE_VERSION}

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/ubuntu-golang"

USER root

ENTRYPOINT ["/sbin/init"]
